### ISSUE TITLE
Missing References?

### ISSUE THREAD

**Issue by Septarius** [tim42/gibbed-justcause3-tools-fork#1]
I noticed that these projects are missing from the fork but are still present in the solution and are needed for compilation.

NDesk.Options
Gibbed.JustCause3.ConvertItem 
ICSharpCode.SharpZipLib.dll
Removed the Gibbed.Avalanche.FileFormats Reference from Gibbed.JustCause3.RenderBlockModel it already had one to Gibbed.JustCause3.FileFormats

Tenatively:
Changed FileFormats to AnyCPU from x86 because it is referenced in AnyCPU projects: Batch, RecurseBatchAndPack, etc. This mismatch could cause problems.

 I added them from r14 of the original SVN in my local copy for now until I know if it is going to work.

**Comment by tim42** [comment]
okay, everything should be fixed now. Thanks for reporting the issue !
I'm new with both C# and VS, and I can't understand why the projects just keep reverting to AnyCPU. Even if they are shown as x86 in visual studio.

bb90483 should fix all the issues you mentioned. Just don't forget to activate nuget if it is disabled.

**Comment by Septarius** [comment]
Pulled the changes down was able to compile straight away.
Thanks for your work on this so far, I had dabbled in what happened after the patch but haven't had enough time to really get into it. If I do get some time I will try to help out where I can.
