### ISSUE TITLE
Release.....

### ISSUE THREAD

**Issue by LokyStaz** [tim42/gibbed-justcause3-tools-fork#5]
Would have been to hard to put a fucking release here instead of forcing us to create a fucking account on another bullshit website to download that Tools !!! WHAT A PAIN !!

**Comment by tim42** [comment]
What a vocabulary. At the time I didn't know binary releases where a thing, but there's absolutely now way I'll do that now.
I mean. You have the sources of the stuff, having the option to build the tools yourself yet you still complain? I could have very well kept the sources for me.
Yet you complain.
